### ISSUE TITLE
Feature request: Support uuid representation

### ISSUE THREAD

**Issue by Greeengooo** [mongomock/mongomock#801] opened 2022-08-18 10:00 UTC
Hi @pcorpet!
I need to update pymongo to a new version 4.2.0. However, as I can see mongomock does not support custom uuid representations yet. Consequently, unit test are failing with `UNSPECIFIED representation` error. This feature will be really handy and it will unblock a lot of people.
Thanks for your work!

**Comment by pcorpet** [comment] 2022-08-19 15:05
I think this is a dupe of #745

**Closed as not planned** 2022-08-19 15:49 UTC
