### ISSUE TITLE
Compatibility between `mongomock` v3.21+ and `pymongo` v2.9-

### ISSUE THREAD

**Issue by wimglenn** [mongomock/mongomock#707] opened 2021-05-11 02:27 UTC
in mongomock <= 3.20.0

```
>>> import mongomock
>>> client = mongomock.MongoClient()
>>> client.db.coll
Collection(Database(mongomock.MongoClient('localhost', 27017), 'db'), 'coll')
>>> client.db.coll
Collection(Database(mongomock.MongoClient('localhost', 27017), 'db'), 'coll')
```

after mongomock >= 3.21.0

```
>>> import mongomock
>>> client = mongomock.MongoClient()
>>> client.db.coll
Collection(Database(mongomock.MongoClient('localhost', 27017), 'db'), 'coll')
>>> client.db.coll
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
... <snipped>
TypeError: read_preference must be an instance of pymongo.read_preference.ReadPreference
```

What's changed, or am I doing something wrong? could not see anything obvious in the changelog

**Comment by pcorpet** [comment] 2021-06-06 13:29
Thanks for opening the bug, do you have `pymongo` installed?

**Comment by pcorpet** [comment] 2021-06-06 13:32
I wasn't able to reproduce using
* `Python 3.9`
* `mongomock 3.21.0`
* with or without `pymongo 3.11.4`

**Comment by wimglenn** [comment] 2021-06-06 18:22
Sorry for not being specific enough - to reproduce the issue, pymongo 2.x should be installed (I was using 2.5.2, but seems to happen with anything between 2.1 and 2.9.x).

There's no error when pymongo is not installed, nor with pymongo >= 3.0 installed.

**Comment by wimglenn** [comment] 2021-12-15 19:11
@pcorpet  ping?

**Comment by pcorpet** [comment] 2021-12-20 22:40
Thanks for updating the bug and sorry for the long silence. I think that you know one obvious way to fix it would be to upgrade pymongo or keep mongomock to an earlier version.

These days `pymongo` is moving on (version 4) now and I'd rather spend time fixing forward rather than keeping backward compatibility. I'll check quickly tonight if I can support pymongo 2.5.2 without too much hastle.

**Comment by pcorpet** [comment] 2021-12-20 23:36
I've tried a bit and couldn't find on how to easily install `pymongo` v2.5.2 or even any v2.x. This is because the `setup.py` uses `setuptools` features that are now gone and I'm not sure how to downgrade `setuptools` in tox. As a result I have a hard time setting up a test environment: I see how I can fix the issue at hand though I'd rather not fix it until we have an automated way to avoid regressions.

**Comment by wimglenn** [comment] 2022-01-03 05:21
The app this was encountered on was still running on Python 2.7.  I've now bitten the bullet and changed it to a Python 3.9 deployment, along with pymongo 3.x upgrade, so we're no longer blocked on mongomock <= 3.20.0 anymore.

Feel free to close this issue.

**Comment by pcorpet** [comment] 2022-01-03 07:58
OK thank you. I'll close this issue then.

**Closed as completed by pcorpet** 2022-01-03 07:58 UTC
Labels: bug
