### ISSUE TITLE
'$geoWithin' is a valid operation but it is not supported by Mongomock yet

### ISSUE THREAD

**Issue by PragmaticCoder** [mongomock/mongomock#627] opened 2020-05-18 01:29 UTC
ERROR - application.main | Server Error: code=500, message='$geoWithin' is a valid operation but it is not supported by Mongomock yet.

This seems to be happening when I try doing something like:
`SomeLocationModel.objects(coordinates__geo_within_center=[(latitude, longitude), radius])`

**Comment by pcorpet** [comment] 2020-05-23 21:37
Yes we do not support geo operations yet, dupe of #315

**Closed as completed by pcorpet** 2020-05-23 21:37 UTC
