### ISSUE TITLE
Please support start_session

### ISSUE THREAD

**Issue by mildewey** [mongomock/mongomock#614] opened 2020-04-02 23:36 UTC
```
conn = mongomock.MongoClient("mongodb://bogus/ngs_dev_pipey?ssl=false")

with conn.start_session():
    pass
```

This will error because `TypeError: 'Database' object is not callable`. I believe this is because start_session is not defined and so that is interpreted as trying to fetch the Database called "start_session", which obviously is not callable.

Related to #435 as they both deal with sessions.

**Comment by pcorpet** [comment] 2020-04-22 20:29
There are two things here:
1. we should return a NotImplementedError instead of a TypeError to be more explicit about what' wrong
2. we should implement sessions at one point, but that's much harder.

**Comment by plollaton** [comment] 2020-04-23 16:13
I'm needing this feature too...pls...rsrsrs

**Comment by dayfine** [comment] 2020-05-06 07:27
Could `start_session` do nothing to start with? i.e. with no session behavior or consistency guarantee, so at least people can use session out of tests?

**Comment by pcorpet** [comment] 2020-08-05 07:55
I'm not familiar with all sessions features, however for the basics: consistency is guaranteed as we don't have network failures nor multiple nodes, but I'm worried about the rolbacks. If someone implements sessions, please raise a `NotImplementedError` when trying to rollback. The logic in `mongomock` is to implement all features are be very loud (raise an error) when a feature is not implemented.

**Comment by pcorpet** [comment] 2020-08-07 06:10
This is now a dupe of #564

**Closed as completed by pcorpet** 2020-08-07 06:10 UTC
Labels: enhancement

**Comment by x-7** [comment] 2023-06-21 12:05
> Could `start_session` do nothing to start with? i.e. with no session behavior or consistency guarantee, so at least people can use session out of tests?

if consistency guarantee is not important for you, you can patch the start_session like below:
@mock.patch.object(mongomock.mongo_client.MongoClient,'start_session')
def test_create(self, mocked_method):
      ...
