### ISSUE TITLE
TypeError with update_many in mongomock

### ISSUE THREAD

**Issue by Triansh** [mongomock/mongomock#724] opened 2021-10-18 17:31 UTC
I was running unit tests for a flask application using pytest. The API works perfectly well in the development environment using pymongo. But when I was running the test for this API, it gave me an error.
```
TypeError: update_many() got an unexpected keyword argument 'array_filters'.
```
I am using a similar type of call in API shown below.
```
mongo_db.model.update_many(
       filter,
       update,
       upsert=False, array_filters=[other_filter]
    )
```
My other tests are working fine, so I don't believe there is an error in patching.

**Comment by pcorpet** [comment] 2022-02-01 22:52
There are two problems in mongomock to run your query:
1. our update method doesn't handle the array_filters kwarg: we should accept it
2. array filters are not implemented.
1 is a bug, but 2 would actually be a feature to be added to mongomock. Feel free to contribute.

**Comment by pcorpet** [comment] 2022-02-02 06:34
What is left is now a duplicate of #567

**Closed as completed by pcorpet** 2022-02-02 06:34 UTC
Labels: enhancement
