### ISSUE TITLE
find_one() with projection returns references to actual (nested) db values

### ISSUE THREAD

**Issue by niklasj** [mongomock/mongomock#752] opened 2022-02-02 10:13 UTC
When a projection is supplied to `find()` or `find_one()` the returned values are the same objects as in the database, meaning the stored values can be indirectly modified:

```python
>>> coll.insert_one({'foo': []})
<pymongo.results.InsertOneResult object at 0x7f6dcabf7c00>
>>> coll.find_one(projection=['foo'])['foo'].append('bar')
>>> coll.find_one()
{'foo': ['bar'], '_id': ObjectId('61fa573e31d53513b8e3500f')}
```

**Comment by pcorpet** [comment] 2022-02-02 10:14
Duplicate of #728

**Closed as completed** 2022-02-02 10:15 UTC
