### ISSUE TITLE
$group with more than one field as _id

### ISSUE THREAD

**Issue by oliverfu89** [mongomock/mongomock#434] opened 2018-08-22 11:25 UTC
python version 3.7.
mongomock version 3.10.0

code to reproduce error:

`import mongomock
import pandas as pd

collection = mongomock.MongoClient().db.collection

documents = [
    {"_id": 1, "item": 'a', "price": 10, "quantity": 2, "ReportingDate": pd.to_datetime("2014-03-01T08:00:00Z")},
    {"_id": 2, "item": 'b', "price": 20, "quantity": 1, "ReportingDate": pd.to_datetime("2014-03-01T09:00:00Z")},
    {"_id": 3, "item": 'c', "price": 5, "quantity": 10, "ReportingDate": pd.to_datetime("2014-03-15T09:00:00Z")},
    {"_id": 4, "item": 'c', "price": 5, "quantity": 20, "ReportingDate": pd.to_datetime("2014-04-04T11:21:39.736Z")},
    {"_id": 5, "item": 'b', "price": 10, "quantity": 10, "ReportingDate": pd.to_datetime("2014-04-04T21:23:13.331Z")},
]

collection.insert_many(documents)

res = collection.aggregate([
    {
        '$group': {'_id': {'item': '$item', 'price': '$price'}}
    },
])`

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-6bb5752d76ec> in <module>()
      1 res = collection.aggregate([
      2     {
----> 3         '$group': {'_id': {'item': '$item', 'price': '$price'}}
      4     },
      5 ])

c:\pkpython\lib\site-packages\mongomock\collection.py in aggregate(self, pipeline, **kwargs)
   1592                     if _id:
   1593                         key_getter = functools.partial(_parse_expression, _id)
-> 1594                         out_collection = sorted(out_collection, key=key_getter)
   1595                         grouped = itertools.groupby(out_collection, key_getter)
   1596                     else:

TypeError: '<' not supported between instances of 'dict' and 'dict'

**Comment by oliverfu89** [comment] 2018-08-22 11:31
Suggested solution:
delete line 1594 in c:\pkpython\lib\site-packages\mongomock\collection.py
The result of a group is not required to be ordered, does it?

**Comment by pcorpet** [comment] 2018-08-22 18:46
I think this is a duplicate of #419 , feel free to reopen if not.
Note that #419 was fixed by #420 which is submitted but not released yet, so you can either wait for a soon to come release, or get mongomock at HEAD from GitHub.

**Closed as completed by pcorpet** 2018-08-22 18:46 UTC
