### ISSUE TITLE
Support generators as return values to `__getitem__` on `mongomock.collection.Cursor`

### ISSUE THREAD

**Issue by akellehe** [mongomock/mongomock#130] opened 2015-02-13 20:58 UTC
If a call to `mongomock.collection.Cursor.__getitem__` expects a `mongomock.collection.Cursor` and gets a `list` (for example in `mongoengine`'s slicing methods `Model.objects.all()[start:finish]`) we get an exception that `list` has no attribute/method `next`. The fix is super-easy, you just have to check here 

https://github.com/vmalloc/mongomock/blob/master/mongomock/collection.py#L876

to see if the return value would be an instance of `list`:

``` python
    def __getitem__(self, index):
        arr = [x for x in self._dataset]
        count = len(arr)
        self._dataset = iter(arr)
        rval = arr[index]
        if isinstance(arr[index], list):
            return iter(arr[index])
        return arr[index]
```

There are a few other methods in the `Cursor` class that could use a little refactoring. `distinct`, for example, might be better as (for the same reason):

``` python
    def distinct(self, key):
        if not isinstance(key, basestring):
            raise TypeError('cursor.distinct key must be a string')
        unique = set()
        for x in iter(self._dataset):
            value = _resolve_key(key, x)
            if value == NOTHING: continue
            unique.add(value)
        self._dataset = (x for x in unique)
        return self
```

**Comment by Kimamisa** [comment] 2016-02-17 13:16
Are you planning to create a PR ?

**Comment by abondis** [comment] 2016-05-31 16:31
I have the issue too with lists. @akellehe fix to return an iterator works for me. I can do a PR, but I'm really not sure what other effects it would have. that said, running `tox` seemed to get success for all the tests.

**Comment by akellehe** [comment] 2016-05-31 16:35
I'll submit a PR this evening.

**Comment by abondis** [comment] 2016-06-07 22:28
I'm running with an issue with a complicated prepared queryset, with the `return iter(arr[index])` fix
````
prepared_qs.first()
  File "mongoengine/mongoengine/queryset/base.py", line 262, in first
    queryset = self.clone()
  File "mongoengine/mongoengine/queryset/base.py", line 678, in clone
    return self.clone_into(self.__class__(self._document, self._collection_obj))
  File "mongoengine/mongoengine/queryset/base.py", line 700, in clone_into
    cls._cursor_obj = self._cursor_obj.clone()
AttributeError: 'listiterator' object has no attribute 'clone'
    cls._cursor_obj = self._cursor_obj.clone()
AttributeError: 'listiterator' object has no attribute 'clone'
````
I didn't identify why or how to reproduce simply, but returning a cursor (which has clone) fixes the problem in my case : `return Cursor(self.collection, functools.partial(iter, arr[index]), self._limit)`
Not sure this should be the solution as I still don't understand the whole internals of mongoengine and mongomock, but maybe that can help ?

**Comment by bcongdon** [comment] 2016-08-07 22:10
Could @abondis' commit be cherry picked into mongomock? I'm running into this issue, and it seems like the fix has been found, but not yet included.

**Comment by pcorpet** [comment] 2018-09-19 20:38
I think that @touilleMan did it in d7aeac1, thanks Emmanuel. please reopen if I'm wrong.

**Closed by pcorpet** 2018-09-19 20:38 UTC
