### ISSUE TITLE
NotImplementedError for sessions!!

### ISSUE THREAD

**Issue by sachinavina** [mongomock/mongomock#569] opened 2019-10-01 04:25 UTC
Wherever session is passed to a method, NotImplementedError is raised, instead can be logged as a warning. So that one can test their units with their other functionality.

**Comment by pcorpet** [comment] 2019-10-01 07:11
@sachinavina, the general rules we have at Mongomock is to behave like `MongoDB` or raise an error. Here we don't want to give users of our library the false feeling that their code is correct. So this is a duplicate of #564.

**Closed as completed by pcorpet** 2019-10-01 07:11 UTC

**Comment by bluenote10** [comment] 2020-05-02 21:53
@pcorpet I like this philosophy in general, but I noticed that it is already not true when it comes to functions that should be atomic. See also the discussion in https://github.com/mongomock/mongomock/issues/145.

From that perspective @sachinavina proposal isn't too far off. Basically mongomock may add a disclaimer that it isn't thread-safe, implying that neither atomicity nor transactions are fully supported for concurrent testing. This would make transactions similar to e.g. `findOneAndUpdate` which one can already use with semi-valid semantics. By applying the same treatment to transactions, one could use them in a productive setting, and yet, it wouldn't be a showstopper for basic testing with mongomock.

**Comment by msenol86** [comment] 2021-12-15 07:19
How can I solve this problem? I am testing a code which start a session but does not use it anywhere.

**Comment by rawmarshmellows** [comment] 2022-07-18 01:16
You can do something like:

```
from contextlib import contextmanager


@contextmanager
def session_with_transaction(client):
    try:
        with client.start_session() as session:
            with session.start_transaction():
                yield client
    except Exception as e:
        if str(e) == "Mongomock does not support sessions yet":
            yield client
        else:
            raise e
```

**Comment by lfoppiano** [comment] 2022-11-17 02:12
@kevinlu1211 could you give some additional background information? Where should this code be placed? 
I tried to place it inside the test file but it doesn't seems to work. Thank you!

**Comment by ggqg** [comment] 2023-02-21 09:43
> @kevinlu1211 could you give some additional background information? Where should this code be placed? I tried to place it inside the test file but it doesn't seems to work. Thank you!

You can use this context manager instead of this function call in your main code
```

with client.start_session() as session:
    with session.start_transaction():
         ...               

```

to 

```
with session_with_transaction(<MongoDBClient instance>) as session:
    ...
```
So every time you get "Mongomock does not support sessions yet" exception in the code the non-session client will be used.

**Comment by sortafreel** [comment] 2023-07-17 12:58
> You can do something like:
> 
> ```
> from contextlib import contextmanager
> 
> 
> @contextmanager
> def session_with_transaction(client):
>     try:
>         with client.start_session() as session:
>             with session.start_transaction():
>                 yield client
>     except Exception as e:
>         if str(e) == "Mongomock does not support sessions yet":
>             yield client
>         else:
>             raise e
> ```

Thank you, it helped a lot! When using with async Mongo (`motor`), it looks like this:

```python
@asynccontextmanager
async def session_with_transaction(
    client: AsyncIOMotorClient,
) -> AsyncIterator[ClientSession]:
    """
    Custom solution to use Mongomock in tests, while continue using trasnactions in production.
    """
    try:
        async with await client.start_session() as s:
            async with s.start_transaction():
                yield s
    except Exception as e:
        if str(e) == "Mongomock does not support sessions yet":
            # Yielding nothing to have session=None and continue using the regular client
            yield None
        else:
            raise e
  ```
  
  and used like this:
  
  ```python
  async with session_with_transaction(client) as s:
  ```
